export const ORDER_STATUSES = [
  'ORDER_PLACED',
  'PRESCRIPTION_VERIFIED',
  'LENS_SOURCING',
  'LENS_CUTTING',
  'FITTING_ASSEMBLY',
  'QUALITY_CHECK',
  'QC_FAILED_REORDER',
  'PACKED',
  'DISPATCHED',
  'DELIVERED',
  'CANCELLED',
];

export const LENS_TYPES = ['SINGLE_VISION', 'BIFOCAL', 'PROGRESSIVE', 'ZERO_POWER', 'CONTACT_LENS'];

export const LENS_INDICES = ['1.50', '1.56', '1.59', '1.61', '1.67', '1.74'];

export const COATINGS = ['ANTI_REFLECTIVE', 'BLUE_CUT', 'PHOTOCHROMIC', 'SCRATCH_RESISTANT', 'UV_PROTECTION'];

export const ORDER_SOURCES = ['WEBSITE', 'STORE', 'MARKETPLACE', 'APP'];

export const STORE_LOCATIONS = ['JAIPUR', 'DELHI', 'MUMBAI'];
